version: "3"
services:
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    networks:
      default:
        ipv4_address: 10.65.81.74
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
  django-app:
    build:
      context: .
      dockerfile: ./docker/uwsgi/Dockerfile
    command: uwsgi --ini docker/uwsgi/uwsgi.ini
    volumes:
      - .:/code
      - django-socket:/home/socket
    networks:
      default:
        ipv4_address: 10.65.81.75
    restart: always
    depends_on:
      - db

  django-web:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/uwsgi_params:/home/uwsgi_params
      - django-socket:/home/socket
      - .:/code
    networks:
      default:
        ipv4_address: 10.65.81.76
      kmndb_network:
    depends_on:
      - django-app

networks:
  default:
    ipam:
      config:
        - subnet: 10.65.81.0/24
  kmndb_network:
    external: true

volumes:
  django-socket:
